name: events-pipeline

on:
  schedule:
    - cron: "0 3 * * *"   # runs daily at 03:00 UTC
  workflow_dispatch:

jobs:
  serpapi-scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Scrape SerpApi events
        run: python events_to_csv.py

      - name: Upload SerpApi artifact
        uses: actions/upload-artifact@v4
        with:
          name: serpapi-events.csv
          path: events_london_on.csv

  western-scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Scrape Western events
        run: python scrape_western_events.py

      - name: Upload Western raw artifact
        uses: actions/upload-artifact@v4
        with:
          name: western-raw.csv
          path: western_events.csv

  western-transform:
    runs-on: ubuntu-latest
    needs: western-scrape
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Download Western raw artifact
        uses: actions/download-artifact@v4
        with:
          name: western-raw.csv
          path: .

      - name: Transform Western events
        run: python transform_western_events.py

      - name: Upload Western transformed artifact
        uses: actions/upload-artifact@v4
        with:
          name: western-events.csv
          path: western_events_transformed.csv

  load-to-db:
    runs-on: ubuntu-latest
    needs: [serpapi-scrape, western-transform]
    env:
      DB_URL: ${{ secrets.DB_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Download SerpApi artifact
        uses: actions/download-artifact@v4
        with:
          name: serpapi-events.csv
          path: .

      - name: Download Western artifact
        uses: actions/download-artifact@v4
        with:
          name: western-events.csv
          path: .

      - name: Load all data into Postgres
        run: python load_events_to_database.py
